<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-URHT7FC" failures="0" tests="4" name="Regression Test 3" time="29.582" errors="0" timestamp="2020-05-01T12:50:47 IST">
  <testcase classname="core.Base" name="@AfterClass afterClass" time="0.933">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utils.Reporting.summaryTable(Reporting.java:122)
at core.Base.flush_ExtentReport(Base.java:203)
at core.Base.afterClass(Base.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase classname="testcases.TC_004_SampleFunc" name="testcase" time="14.017"/>
  <testcase classname="testcases.TC_002_SampleFunc" name="testcase" time="14.315"/>
  <testcase classname="testcases.TC_003_SampleFunc" name="testcase" time="14.381"/>
  <testcase classname="testcases.TC_001_SampleFunc" name="testcase" time="14.485"/>
</testsuite> <!-- Regression Test 3 -->
